name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Compile C++ Code
      run: g++ -Wall -std=c++17 "Programming Assignment.cpp" -o my_assignment
      working-directory: "./Programming Assignment/Programming Assignment"
